# Generated by Django 6.0.7 on 2026-08-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('Village', 'Village'), ('Ward', 'Ward'), ('School', 'School'), ('Health Centre', 'Health Centre'), ('Tourist Site', 'Tourist Site'), ('Project', 'Project')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='locations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
