# Generated by Django 6.0.7 on 2026-08-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('Beach', 'Beach'), ('Historical Site', 'Historical Site'), ('Festival', 'Festival'), ('Cultural Centre', 'Cultural Centre'), ('Nature', 'Nature'), ('Hotel', 'Hotel'), ('Restaurant', 'Restaurant')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tourism/')),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
