# Generated by Django 6.0.7 on 2026-08-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('event_type', models.CharField(choices=[('Government', 'Government'), ('Community', 'Community'), ('Festival', 'Festival'), ('Youth', 'Youth'), ('Women', 'Women'), ('Education', 'Education'), ('Health', 'Health'), ('Sports', 'Sports')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('organizer', models.CharField(blank=True, max_length=255)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
