# Generated by Django 6.0.7 on 2026-08-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='village_head',
            field=models.CharField(blank=True, help_text='Name of the Eteidung / Village Head', max_length=255),
        ),
    ]
