# Generated by Django 6.0.7 on 2026-09-22 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villages', '0002_alter_village_village_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clans', to='villages.clancategory'),
        ),
    ]
