# Generated by Django 6.0.7 on 2026-08-24 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
        ('villages', '0002_alter_village_village_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProminentIndigene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='prominent_indigenes/')),
                ('title', models.CharField(blank=True, help_text='e.g. Professor, Chief, Dr., Hon., etc.', max_length=255)),
                ('profession', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(blank=True, help_text='Current or notable position', max_length=255)),
                ('community', models.CharField(blank=True, max_length=255)),
                ('short_bio', models.TextField(blank=True)),
                ('biography', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=True, help_text='Show this person on the homepage')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prominent_indigenes', to='villages.clan')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prominent_indigenes', to='villages.ward')),
            ],
            options={
                'verbose_name': 'Prominent Indigene',
                'verbose_name_plural': 'Prominent Indigenes',
                'ordering': ['order', 'name'],
            },
        ),
    ]
