# Generated by Django 6.0.7 on 2026-08-26 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_prominentindigene'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_line_1', models.CharField(default='Building a Greater', help_text='First part of the title', max_length=100)),
                ('title_highlight', models.CharField(default='Uruan', help_text='Highlighted text (e.g., yellow text)', max_length=100)),
                ('title_line_2', models.CharField(default='Together', help_text='Trailing part of the title', max_length=100)),
                ('subtitle', models.TextField(help_text='Main description text under the title')),
                ('background_image', models.ImageField(blank=True, help_text='Background hero image', null=True, upload_to='hero/')),
                ('primary_button_text', models.CharField(default='Latest News', max_length=50)),
                ('primary_button_url', models.CharField(default='#', max_length=255)),
                ('secondary_button_text', models.CharField(default='Our Projects', max_length=50)),
                ('secondary_button_url', models.CharField(default='#', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Only one active hero section should be displayed.')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='HeroStatCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text="Stat value e.g., '120K+', '52'", max_length=50)),
                ('label', models.CharField(help_text="Stat label e.g., 'Population', 'Communities'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the grid')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='about.herosection')),
            ],
            options={
                'verbose_name': 'Hero Stat Card',
                'verbose_name_plural': 'Hero Stat Cards',
                'ordering': ['order'],
            },
        ),
    ]
