# Generated by Django 6.0.7 on 2026-08-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_herosection_herostatcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, help_text='Main background image for the homepage hero section.', null=True, upload_to='home/hero/')),
                ('heading', models.CharField(default='Building a Greater', help_text='Main hero heading.', max_length=255)),
                ('highlighted_text', models.CharField(default='Uruan', help_text='Text displayed in yellow.', max_length=100)),
                ('heading_suffix', models.CharField(default='Together', help_text='Text displayed after the highlighted text.', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Hero introductory description.')),
                ('primary_button_text', models.CharField(default='Latest News', max_length=100)),
                ('primary_button_url', models.CharField(default='/news/', max_length=255)),
                ('secondary_button_text', models.CharField(default='Our Projects', max_length=100)),
                ('secondary_button_url', models.CharField(default='/projects/', max_length=255)),
                ('population', models.CharField(default='120K+', max_length=50)),
                ('population_label', models.CharField(default='Population', max_length=100)),
                ('communities', models.CharField(default='52', max_length=50)),
                ('communities_label', models.CharField(default='Communities', max_length=100)),
                ('schools', models.CharField(default='85+', max_length=50)),
                ('schools_label', models.CharField(default='Schools', max_length=100)),
                ('health_centres', models.CharField(default='12', max_length=50)),
                ('health_centres_label', models.CharField(default='Health Centres', max_length=100)),
                ('markets', models.CharField(default='8', max_length=50)),
                ('markets_label', models.CharField(default='Markets', max_length=100)),
                ('projects', models.CharField(default='50+', max_length=50)),
                ('projects_label', models.CharField(default='Projects', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Only the active hero will appear on the homepage.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Hero',
                'verbose_name_plural': 'Homepage Hero',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='herostatcard',
            name='hero',
        ),
        migrations.DeleteModel(
            name='HeroSection',
        ),
        migrations.DeleteModel(
            name='HeroStatCard',
        ),
    ]
