# Generated by Django 6.0.7 on 2026-08-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilLeadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='council_leadership/')),
                ('title', models.CharField(blank=True, help_text='e.g. Hon., Barr., Engr., Dr., Chief, etc.', max_length=100)),
                ('council_type', models.CharField(choices=[('Executive', 'Executive Council'), ('Legislative', 'Legislative Council')], max_length=20)),
                ('designation', models.CharField(max_length=100)),
                ('custom_designation', models.CharField(blank=True, help_text='Use this if the designation is not covered above.', max_length=255)),
                ('ward', models.CharField(blank=True, max_length=255)),
                ('community', models.CharField(blank=True, max_length=255)),
                ('political_party', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=255)),
                ('qualification', models.CharField(blank=True, max_length=500)),
                ('biography', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('chairman_message', models.TextField(blank=True, help_text="Official message from the Executive Chairman. This field is primarily used for the Chairman's profile.")),
                ('message_title', models.CharField(blank=True, default="Chairman's Message", max_length=255)),
                ('date_assumed_office', models.DateField(blank=True, null=True)),
                ('date_left_office', models.DateField(blank=True, null=True)),
                ('current', models.BooleanField(default=True, help_text='Is this person currently serving?')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('office_address', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=True, help_text='Display this person on the leadership page.')),
                ('show_on_homepage', models.BooleanField(default=False, help_text='Display this leader on the homepage.')),
                ('show_chairman_message', models.BooleanField(default=False, help_text="Display this person's message as Chairman's Message.")),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls the display order.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Council Leadership',
                'verbose_name_plural': 'Council Leadership',
                'ordering': ['council_type', 'order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='PastChairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(blank=True, help_text='e.g. Hon., Barr., Engr., Dr., Chief, etc.', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='past_chairmen/')),
                ('tenure_start', models.DateField(blank=True, null=True)),
                ('tenure_end', models.DateField(blank=True, null=True)),
                ('tenure_description', models.CharField(blank=True, help_text='e.g. 2015 - 2018', max_length=255)),
                ('profession', models.CharField(blank=True, max_length=255)),
                ('qualification', models.CharField(blank=True, max_length=500)),
                ('community', models.CharField(blank=True, max_length=255)),
                ('clan', models.CharField(blank=True, max_length=255)),
                ('biography', models.TextField(blank=True)),
                ('service_summary', models.TextField(blank=True, help_text="Summary of the chairman's administration.")),
                ('achievements', models.TextField(blank=True, help_text='Major projects, policies and accomplishments recorded during the administration.')),
                ('legacy', models.TextField(blank=True, help_text='Describe the lasting impact of the administration.')),
                ('challenges', models.TextField(blank=True, help_text='Major challenges encountered during the tenure.')),
                ('major_projects', models.TextField(blank=True, help_text='List major infrastructure, education, health, roads, water or other projects undertaken.')),
                ('awards', models.TextField(blank=True, help_text='Awards, honours and recognitions received.')),
                ('featured', models.BooleanField(default=True, help_text='Display this former chairman on the website.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Past Chairman',
                'verbose_name_plural': 'Past Chairmen',
                'ordering': ['-tenure_end', 'order', 'full_name'],
            },
        ),
        migrations.RemoveField(
            model_name='chairmanachievement',
            name='chairman',
        ),
        migrations.DeleteModel(
            name='ChairmanMessage',
        ),
        migrations.DeleteModel(
            name='Chairman',
        ),
        migrations.DeleteModel(
            name='ChairmanAchievement',
        ),
    ]
