# Generated by Django 6.0.7 on 2026-08-26 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0002_councilleadership_pastchairman_and_more'),
        ('villages', '0002_alter_village_village_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraditionalLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(blank=True, help_text='e.g. His Royal Majesty, HRM, Chief, Prince, etc.', max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='traditional_leaders/')),
                ('leadership_type', models.CharField(choices=[('Paramount Ruler', 'Paramount Ruler'), ('Clan Head', 'Clan Head'), ('Village Head', 'Village Head'), ('Chief', 'Chief'), ('Regent', 'Regent'), ('Traditional Council', 'Traditional Council'), ('Other', 'Other')], default='Other', max_length=50)),
                ('traditional_title', models.CharField(help_text='e.g. Paramount Ruler of Uruan, Clan Head of ..., Village Head of ...', max_length=255)),
                ('custom_designation', models.CharField(blank=True, help_text='Use this where the standard leadership type does not apply.', max_length=255)),
                ('community', models.CharField(blank=True, max_length=255)),
                ('village', models.CharField(blank=True, max_length=255)),
                ('traditional_council', models.CharField(blank=True, help_text='Name of the Traditional Council, where applicable.', max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=255)),
                ('qualification', models.CharField(blank=True, max_length=500)),
                ('biography', models.TextField(blank=True)),
                ('date_of_ascension', models.DateField(blank=True, help_text='Date the leader assumed the traditional office.', null=True)),
                ('date_left_office', models.DateField(blank=True, null=True)),
                ('current', models.BooleanField(default=True, help_text='Is this person currently holding the traditional office?')),
                ('reign_description', models.CharField(blank=True, help_text='e.g. 2018 - Present', max_length=255)),
                ('achievements', models.TextField(blank=True, help_text='Major achievements and contributions to the community.')),
                ('community_development', models.TextField(blank=True, help_text='Community development initiatives and contributions.')),
                ('cultural_contributions', models.TextField(blank=True, help_text='Contributions to culture, traditions and heritage.')),
                ('legacy', models.TextField(blank=True, help_text="Describe the leader's lasting traditional or community legacy.")),
                ('palace_address', models.TextField(blank=True, help_text='Palace or official traditional council address.')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('featured', models.BooleanField(default=True, help_text='Display this traditional leader on the website.')),
                ('show_on_homepage', models.BooleanField(default=False, help_text='Display this traditional leader on the homepage.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls the display order.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traditional_leaders', to='villages.clan')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traditional_leaders', to='villages.ward')),
            ],
            options={
                'verbose_name': 'Traditional Leader',
                'verbose_name_plural': 'Traditional Leaders',
                'ordering': ['-current', 'order', 'full_name'],
            },
        ),
    ]
